### PR TITLE
WebRTC functionality

### PR DESCRIPTION
**Pull request by theMostCuriousHomunculus**
note: screen share functionality and audio only call initiation are not yet implemented.  will remove draft status after those are working.

1. run "docker-compose up -d" to spin up the containers
2. create two accounts and note their mongoDB generated IDs (you can find this by logging into the account and then clicking the "My Profile" navigation link and noting the hexadecimal parameter in the url)
3. open a browser tab and navigate to "http://localhost:6969/conversation/x&y", where x and y are the two hexadecimal account IDs
4. you should see a basic screen that just tells you that you aren't invited to the conversation
5. log into one of the accounts
6. duplicate the browser tab and log into the other account in the duplicated tab
7. you should be able to type into the input field and send a message that will render in both tabs
8. hover over the speed dial floating plus sign icon button thing in the top left corner and then click on the "Share Camera" icon button
9. if this is your first time, your browser should ask whether you want to allow localhost:6969 access to your camera and microphone
10. select yes to that prompt; if you select no, you will have to go into your browser permissions settings and grant or reset permissions for localhost:6969
11. after a second or two the video feed from your camera should begin playing on both tabs and the audio feed should also play on the tab which is not the one sharing camera yet
12. on the other tab, choose to share your camera feed as well and note that the video feed should now be replicated twice in both tabs (because in this instance, the users are on the same device sharing the same camera feed)
13. you should be able to toggle the audio and/or video on and off which should cut the feed out in both tabs; toggle them back on and the feed should resume

### CODE REVIEW

**Comment by theMostCuriousHomunculus** [comment]
@RoryDeken , could you please enter spanish translations for the new multilingual dictionary entries?

**Comment by theMostCuriousHomunculus** [comment]
@RoryDeken - finally finished!  seems to work as intended.  feel free to review as thoroughly or as cursorily as you want.  just go ahead and hit that approve button whenever you're satisfied

**Comment by RoryDeken** [comment]
@theMostCuriousHomunculus I am able to get everything setup and running but for some reason the web server isn't resolving.

Screenshot 2023-01-23 at 11 14 28 AM

The db server is working but I am not getting any data back at localhost:6969 or the default localhost:24678

**Comment by theMostCuriousHomunculus** [comment]
Weird; it was working for me. Maybe try deleting the image in docker desktop and rerunning? It looks like it isn't even giving you any error logs since it's not even spinning up that container ...

**Comment by RoryDeken** [comment]
> Actually, scratch that; worked on the nginx issue most of the day yesterday so was seeing 3 containers but on the branch you're looking at there are still only 2. So when you go to localhost:6969 in the browser do you see the app? It's just not pulling data from the database?

There are only 2 containers that are pulled down when I docker compose ❓

**Comment by RoryDeken** [comment]
> > Actually, scratch that; worked on the nginx issue most of the day yesterday so was seeing 3 containers but on the branch you're looking at there are still only 2. So when you go to localhost:6969 in the browser do you see the app? It's just not pulling data from the database?
> 
> There are only 2 containers that are pulled down when I docker compose ❓

It looks like it is missing the app container. I see the containers on port:24678 and the db server on 27017 but no container that is listening on 6969

**Review by RoryDeken — APPROVED** [review]
Looks good ready to 🚀

**Pull request merged**
